@startuml 
title Data Provenance - September 2023

entity Data

abstract class Metadata {
    identifier : String[1..1] - A unique label identifying the provenance metadata of the current dataset
    lineage : WhereFrom[0..*] - Identifiers of pointers of metadata representing the data which comprise the current dataset
    source : Source[1..1] Identifies the origin (person, organization, system, device, etc) of the current dataset
    legalRights : LegalRights[0..*] - Identifies the legal or regulatory framework applicable to the current dataset, along with the required data attributions, associated copyright or trademark, and localization and processing requirements
    privacyProtection : PrivacyProtection[0..*] - Identifies any types of sensitive data associated with the current dataset and any privacy enhancing techniques applied
    generationData : dateTime[1..1] - Timestamp marking the creation of the current dataset
    dataType : DataType[1..*] - Identifies the data type contained in the current set, and provides insights into how the data is organized, its potential use cases, and the challenges associated with handling and using it
    generationMethod : GenerationMethod[1..*] - Identifies how the data was produced (data mining, machine-generated, IoT sensors, etc.)
    intendedUseAndRestrictions : UseAndRestrictions[0..*] - Identifies the intended use of the data and which downstream audiences should not be allowed access to the current dataset
}

Metadata *-down- WhereFrom 
Metadata *-down- Source 
Metadata *-down- LegalRights 
Metadata *-down- PrivacyProtection 
Metadata *-down- DataType
Metadata *-down- GenerationMethod
Metadata *-down- UseAndRestrictions
Metadata -left-> Data

abstract class WhereFrom {
    Identifiers of pointers of metadata representing the data which comprise the current dataset
    ----
    uniqueId : String[0..1] - Universal Provenance Metadata Unique Identifier
    blockId : String[0..1] - Blockchain ledger ID
    otherId : String[0..1] - Other ID
}

abstract class Source {
    Identifies the origin (person, organization, system, device, etc) of the current dataset
    ----
    userName : String[0..1] - Username
    organizationName : String[0..1] - Organization name
    software : String[0..1] - Software name
    system : String[0..1] - System name
    machine : String[0..1] - Machine name
    sensor : String[0..1] - Sensor/IoT device name
    file : String[0..1] - Filename
    ip : String[0..1] - Network name or IP address
    other : String[0..1] - other 
}

abstract class LegalRights {
    Identifies the legal or regulatory framework applicable to the current dataset, along with the required data attributions, associated copyright or trademark, and localization and processing requirements
    ----
    attributionRights : String[0..1] - Attribution rights
    ipRights : String[0..1] - Copyrights or trademarks
    locationRestriction : String[0..1] - Required data storage or processing geolocation
    laws : LawsAndRegulations[0..1] - Applicable laws and regulations
}

LegalRights -down- LawsAndRegulations

enum LawsAndRegulations {
CHILDRENS_ONLINE_PRIVACY_PROTECTION_ACT_COPPA : Children’s Online Privacy Protection Act (COPPA)
ARGENTINA_PERSONAL_DATA_PROTECTION_ACT_PDPA : Argentina: Personal Data Protection Act (PDPA)
BAHRAIN_PERSONAL_DATA_PROTECTION_LAW_PDPL : Bahrain: Personal Data Protection Law (PDPL)
BRAZIL_LEI_GERAL_DE_PROTECAO_DE_DADOS_PESSOAIS_LGPD : Brazil: Lei Geral de Proteção de Dados Pessoais (LGPD)
CALIFORNIA_CONSUMER_PRIVACY_ACT_CCPA : California Consumer Privacy Act (CCPA)
CALIFORNIA_ONLINE_PRIVACY_PROTECTION_ACT_OF_2003_CALOPPA : California Online Privacy Protection Act of 2003 (CalOPPA)
CANADA_PERSONAL_INFORMATION_PROTECTION_AND_ELECTRONIC_DOCUMENTS_ACT_PIPEDA : Canada: Personal Information Protection and Electronic Documents Act (PIPEDA)
CHINA_NEXT_GENERATION_ARTIFICIAL_INTELLIGENCE_DEVELOPMENT_PLAN : China Next Generation Artificial Intelligence Development Plan
CHINA_SHANGHAI_REGULATIONS_ON_PROMOTING_THE_DEVELOPMENT_OF_THE_AI_INDUSTRY : China: Shanghai Regulations on Promoting the Development of the AI Industry
COLORADO_PRIVACY_ACT_COLOPA : Colorado Privacy Act (ColoPA)
CONNECTICUT_DATA_PRIVACY_ACT_CDPA : Connecticut Data Privacy Act (CDPA)
EUROPEAN_UNION_GENERAL_DATA_PROTECTION_REGULATION_GDPR : European Union: General Data Protection Regulation (GDPR)
GRAMM_LEACH_BLILEY_ACT_GLBA : Gramm-Leach-Bliley Act (GLBA)
HEALTH_INSURANCE_PORTABILITY_AND_ACCOUNTABILITY_ACT_HIPAA : Health Insurance Portability and Accountability Act (HIPAA)
ISRAEL_PRIVACY_PROTECTION_DATA_SECURITY_REGULATIONS : Israel: Privacy Protection (Data Security) Regulations
JAPAN_ACT_ON_THE_PROTECTION_OF_PERSONAL_INFORMATION_APPI : Japan: Act on the Protection of Personal Information (APPI)
KENYA_DATA_PROTECTION_ACT : Kenya: Data Protection Act
MAURITIUS_DATA_PROTECTION_ACT_2017_DPA : Mauritius: Data Protection Act, 2017 (DPA)
NEW_ZEALAND_PRIVACY_ACT_2020 : New Zealand: Privacy Act 2020
NIGERIA_DATA_PROTECTION_REGULATION_NDPR : Nigeria Data Protection Regulation (NDPR)
QATAR_LAW_NO_13_OF_2016 : Qatar: Law No. 13 of 2016
SOUTH_AFRICA_PROTECTION_OF_PERSONAL_INFORMATION_ACT_POPIA : South Africa: Protection of Personal Information Act (POPIA)
SOUTH_KOREA_PERSONAL_INFORMATION_PROTECTION_ACT_PIPA : South Korea: Personal Information Protection Act (PIPA)
TURKEY_LAW_ON_PROTECTION_OF_PERSONAL_DATA_NO_6698 : Turkey: Law on Protection of Personal Data No. 6698
UGANDA_DATA_PROTECTION_AND_PRIVACY_ACT_2019 : Uganda: Data Protection and Privacy Act, 2019
URUGUAY_DATA_PROTECTION_ACT : Uruguay: Data Protection Act
UTAH_CONSUMER_PRIVACY_ACT_UCPA : Utah Consumer Privacy Act (UCPA)
VIRGINIA_CONSUMER_DATA_PROTECTION_ACT_VCDPA : Virginia Consumer Data Protection Act (VCDPA)
}

abstract class PrivacyProtection {
    Identifies any types of sensitive data associated with the current dataset and any privacy enhancing techniques applied
    ----
    protectedDataClassification : ProtectedDataClassification[0..1] 
    appliedPrivacy : AppliedPrivacy[0..1]
    otherPrivacy : String[0..1]
}

PrivacyProtection -down- ProtectedDataClassification
PrivacyProtection -down- AppliedPrivacy

enum ProtectedDataClassification {
PROTECTED_HEALTH_INFORMATION_PHI : Protected Health Information (PHI)
PERSONALLY_IDENTIFIABLE_INFORMATION_PII : Personally Identifiable Information (PII)
HEALTH_INSURANCE_PORTABILITY_AND_ACCOUNTABILITY_ACT_HIPAA : Health Insurance Portability and Accountability Act (HIPAA)
PERSONAL_FINANCIAL_INFORMATION : Personal Financial Information     
}

enum AppliedPrivacy {
DATA_GENERATION_SYNTHETIC : Data generation (synthetic)
DATA_ANONYMIZATION : Data anonymization
DATA_TRANSFORMATION_HOMOMORPHIC_ENCRYPTION : Data transformation (homomorphic encryption)    
}

abstract class DataType {
    Identifies the data type contained in the current set, and provides insights into how the data is organized, its potential use cases, and the challenges associated with handling and using it
    ----
    structuredMediaType : MediaType[0..1] http://www.iana.org/assignments/media-types/
    structuredOther : String[0..1] - structured types not defined by Media-Types
    unStructuredMediaType : MediaType[0..1] http://www.iana.org/assignments/media-types/
    unStructuredOther : String[0..1] - unstructured types not defined by Media-Types
}



abstract class GenerationMethod {
    Identifies how the data was produced (data mining, machine-generated, IoT sensors, etc.)
    ----
    web : Web[0..1]
    feeds : Feeds[0..1]
    syndication : Syndication[0..1]
    dataMining : DataMining[0..1]
    machineGenerated : MachineGenerated[0..1]
    sensor : Sensor[0..1]
    socialMedia : SocialMedia[0..1]
    userGenerated : UserGenerated[0..1]
    primaryUserSourced : PrimaryUserSourced[0..1]
    other : String[0..1] - Other method not coded
}
 
GenerationMethod -down- Web
GenerationMethod -down- Feeds
GenerationMethod -down- Syndication
GenerationMethod -down- DataMining
GenerationMethod -down- MachineGenerated
GenerationMethod -down- Sensor
GenerationMethod -down- SocialMedia
GenerationMethod -down- UserGenerated
GenerationMethod -down- PrimaryUserSourced


enum Web {
TEXUAL : Texual
STRUCTURED : Structured
METADATA : Metadata
SOCIALMEDIA : SocialMedia
NEWS : News
}
enum Feeds {
RSS : RSS
API : API
REALTIMEDATABASEINFO : RealTimeDatabaseInfo
INTERVALTIMEDDATABASEINFO : IntervalTimedDatabaseInfo
FILEFEEDINFO : FileFeedInfo
}
enum Syndication {
NEWSFEED : NewsFeed
FINANCIALFEED : FinancialFeed
SOCIALMEDIA : SocialMedia
PRODUCTCATALOG : ProductCatalog
}
enum DataMining {
ASSOCIATION_RULE : Association Rule
CLASSIFICATION : Classification
CLUSTERING : Clustering
REGRESSION : Regression
ANOMALY_DETECTION : Anomaly Detection
SEQUENCING : Sequencing
}
enum MachineGenerated {
SYNTHETIC : Synthetic
GENERATIVE : Generative
TWIN : Twin
MACHINE_2_MACHINE_M2M : Machine-2-Machine (M2M)
AI_INFERRED : AI inferred
XR_ARVRMR : XR (AR,VR,MR)
}
enum Sensor {
ENVIRONMENTAL : Environmental
MOTION_AND_LOCATION : Motion & Location
HEALTH : Health
BIOMETRIC : Biometric
ENERGY_CONSUMPTION : Energy Consumption
INDUSTRAL_SENSOR : Industral Sensor
VEHICLE_AND_TRANSPORTATION : Vehicle & Transportation
SECURITY_AND_SERVEILLANCE : Security & Serveillance
AGRICULTURE_AND_ENVIRONMENT : Agriculture & Environment
}
enum SocialMedia {
TEXT_BASED : Text Based
MULTIMEDIA : Multimedia
REVIEWS_AND_RATINGS : Reviews and Ratings
UPDATES : Updates
Q_AND_AS : Q&As
COLLABORATIVE : Collaborative
CREATIVE : Creative
}
enum UserGenerated {
CLICKSTREAM : Clickstream
SOCIAL_MEDIA : Social Media
BEHAVIOR : Behavior
RATINGS_AND_REVIEWS : Ratings & Reviews
MULTIMEDIA : Multimedia
TEXTUAL_SURVEY : Textual/Survey
}
enum PrimaryUserSourced {
SURVEY : Survey
INTERVIEW : Interview
EVENT : Event
}

abstract class UseAndRestrictions {
    Identifies the intended use of the data and which downstream 
    audiences should not be allowed access to the current dataset
    ----
    intendedUse : IntendedUse[0..1]
    otherIntendedUse : String[0..1] - Other Intended Use not coded
    restrictedAudience : RestrictedAudience[0..1] 
    otherRestrictedAudience : String[0..1] - Other Restricted Audience not coded
}

UseAndRestrictions -down- IntendedUse
UseAndRestrictions -down- RestrictedAudience

enum IntendedUse {
MACHINE_LEARNING_ML : Machine Learning (ML)
NATURAL_LANGUAGE_PROCESSING_NLP : Natural Language Processing (NLP)
EXPERT_SYSTEMS : Expert Systems
VISION : Vision
SPEECH : Speech
PLANNING : Planning
ROBOTICS : Robotics
}
enum RestrictedAudience {
FEDERAL_GOVERNMENT : Federal Government 
STATE_GOVERNMENT : State Government 
LOCAL_GOVERNMENT : Local Government
NOT_FOR_PROFIT_CHARITIES : Not-for-profit / Charities
ACADEMIA_RESEARCH : Academia / Research
COMMERCIAL_BUSINESS : Commercial / Business
}

@enduml