@startuml 

title Data Provenance

abstract class Metadata {
  agent : String[0..*] - **W3C** The Agent is something or someone who takes action in the creation of the data. \n\tThe organization, software, system sending or capturing the data 
  entity : Entity[0..*] - **W3C** The Entity is something that is manipulated by the Agent in the creation of the data. \n\tCaptures lineage when data are derived or transformed
  location : String[0..*] - **W3C** Location where data was captured, usually GPS, zip or country code
  whenCollected : dateTime|period[0..*] - **W3C** when was the data captured, sourced, or manipulated
  generationMethod : String[0..*] - **W3C** How the data was sourced e.g., web scrapings, user-generated \n\tcontent or manipulated e.g., converted, combined, cleaned
  consentFramework : String[0..*] - Consent methods applied to data and implies processing options
  biasEthics : String[0..*] - Data characteristics that inform bias and ethics; could include anonymization or obfuscation
  intellectualProperty : String[0..*] - Licenses, patents, rights to use the data and work generated using the data 
  usage : String[0..*] -  Indicates data usage purpose or limitations, other than consent and intellectual property rights
}
Metadata *-down- Entity 
Metadata -left-> Data

abstract class Entity {
    howUsed : String[1..1] <<revision, quotation, source, removal>>
    what : Reference[1..1] <<Any>>
}

@enduml
